---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: quay.io/egi/umd4:centos7
  - name: centos6
    image: quay.io/egi/umd4:centos6
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: top-bdii
verifier:
  name: testinfra
  lint:
    name: flake8
