---
# Travis template for an EGI-styled role
language: python
python:
  - '2.7'
sudo: required
services:
  - docker
env:
  md_ignore: R1  # Which markdownlint rules to ignore
before_install:
install:
  - pip install -r requirements.txt  # The packages necessary for running the tests.
before_script:
  - > # Lint all the markdown files
      for file in `find . -maxdepth 2 -name "*.md"` ;  do
      markdownlint --ignore $md_ignore $file ;
      done
  - molecule lint
  - molecule destroy
script:
  - molecule dependency
  - molecule syntax
  - molecule create
  - molecule prepare
  - molecule converge
  - molecule idempotence
  - molecule side_effect
  - molecule verify
after_success:
  - molecule destroy
after_failure:
  - molecule destroy
before_deploy:
deploy:
after_deploy:
after_script:
# Add your notifications here.
# Use travis encrypt to add api tokens.
notifications:
#   slack:
#     secure:
  webhooks: "https://galaxy.ansible.com/api/v1/notifications/"
