---
# Travis template for an EGI-styled role
language: python
python:
  - '2.7'
sudo: required
services:
  - docker
env:
  - md_ignore=R1  # Which markdownlint rules to ignore
  - SCENARIO=default
  - SCENARIO=site-bdii
before_install:
install:
  - pip install -r requirements.txt  # The packages necessary for running the tests.
before_script:
  - > # Lint all the markdown files
      for file in `find . -maxdepth 2 -name "*.md"` ;  do
      markdownlint --ignore $md_ignore $file ;
      done
  - molecule -s $SCENARIO lint 
  - molecule -s $SCENARIO destroy
script:
  - molecule -s $SCENARIO dependency
  - molecule -s $SCENARIO syntax
  - molecule -s $SCENARIO create
  - molecule -s $SCENARIO prepare
  - molecule -s $SCENARIO converge
  - molecule -s $SCENARIO idempotence
  - molecule -s $SCENARIO side-effect
  - molecule -s $SCENARIO verify
after_success:
  - molecule -s $SCENARIO destroy
after_failure:
  - molecule -s $SCENARIO destroy
before_deploy:
deploy:
after_deploy:
after_script:
# Add your notifications here.
# Use travis encrypt to add api tokens.
notifications:
#   slack:
#     secure:
  webhooks: "https://galaxy.ansible.com/api/v1/notifications/"
