---
# Tasks to configure bdii
- name: "Ensure the bdii user groups - {{ bdii_user['groups'] }}  present"
  group:
    name: "{{ item }}"
    state: present
    system: false
  with_items: "{{ bdii_user['groups']}}"

- name: Ensure users are present
  user:
    name: "{{ bdii_user['name'] }}"
    create_home: false
    uid: 1001
    force: true
    groups: "{{ item }}"
    group: "{{ bdii_user['group'] }}"
    home: "{{ bdii_user['home'] }}"
    state: present
    skeleton: false
    shell: "{{ bdii_user['shell'] }}"
    comment: "{{ bdii_user['comment']}}"
  with_items: "{{ bdii_user['groups'] }}"

- name: Ensure directories exists
  file:
    path: "{{ item }}"
    owner: "{{ bdii_user['name']}}"
    mode: 0774
    state: directory
    group: "{{ bdii_user['group']}}"
  with_items:
    - "{{ bdii['core']['data_dir']}}"
    - "{{ bdii['core']['log_dir']}}"

- name: Template BDII_CONFIG
  template:
    dest: /etc/bdii/DB_CONFIG
    src: etc/bdii/DB_CONFIG.j2
    owner: root
    group: root

- name: Template DB_CONFIG for the bdii type
  template:
    dest: "/etc/bdii/DB_CONFIG_{{ bdii_type }}"
    src: "etc/bdii/DB_CONFIG_{{ bdii_type }}.j2"
    owner: root
    group: root
  when: bdii_type is defined
