---
# Tasks to configure bdii
- name: "Ensure the bdii user groups - {{ bdii_user['groups'] }}  present"
  group:
      name: "{{ item }}"
      state: present
      system: no
  with_items: "{{ bdii_user['groups']}}"

- name: Ensure users are present
  user:
      name: "{{ bdii_user['name'] }}"
      create_home: no
      uid: 1001
      groups: "{{ item }}"
      group: "{{ bdii_user['group'] }}"
      home: "{{ bdii_user['home'] }}"
      state: present
      skeleton: false
      shell: "{{ bdii_user['shell'] }}"
      comment: "{{ bdii_user['comment']}}"
  with_items: "{{ bdii_user['groups'] }}"

- name: Ensure data directory exists
  file:
      path: "{{ bdii['core']['data_dir']}}"
      owner: "{{ bdii_user['name']}}"
      mode: 0644
      state: directory
      group: "{{ bdii_user['group']}}"
