---
# Tasks for site-bdii configuration
- name: Install site-bdii specific packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ bdii_vars[bdii_type]['packages'][(ansible_os_family |lower)]}}"

- name: Ensure Static Info Directory
  file:
    path: "{{ item }}"
    owner: "{{ bdii_user['name'] }}"
    state: directory
    group: "{{ bdii_user['group'] }}"
  loop:
    - /etc/glite-info-static/
    - /etc/glite-info-static/site
    - /etc/bdii/gip/

- name: Template configuration files
  template:
    dest: "/{{ item }}"
    src: "{{ item }}.j2"
    mode: 0644
    owner: "{{ bdii_user['name'] }}"
  loop:
    - "{{ bdii_vars['site']['slapd_config_file']}}"
    - "{{ bdii_vars['site']['static_info_config_file'] }}"
    - "{{ bdii_vars['site']['service_info_provider_config_file'] }}"
    - "{{ bdii_vars['site']['config_file']}}"
