---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos7
    box: geerlingguy/centos7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: top-bdii-vagrant
verifier:
  name: inspec
  lint:
    name: rubocop
