---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos7
    box: geerlingguy/centos7
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 2170, host: 2170"
    cpus: 1
    memory: 1024
  - name: centos6
    box: geerlingguy/centos6
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 2170, host: 21700"
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: top-bdii-vagrant
verifier:
  name: inspec
  lint:
    name: rubocop
