---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos6
    image: centos:6
    exposed_ports:
      - "2170"
  - name: centos7
    image: centos:7
    exposed_ports:
      - "2170"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: site-bdii
verifier:
  name: testinfra
  lint:
    name: flake8
