---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos6
    image: centos:6
  - name: centos7
    image: centos:7
  # - name: ubuntu
  #   image: ubuntu:trusty
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
